# Generated by Django 3.0.5 on 2020-07-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200704_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
