# Generated by Django 3.0.5 on 2020-07-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200704_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postby',
        ),
    ]
