# Generated by Django 3.0.5 on 2020-07-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200705_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com',
            new_name='coms',
        ),
    ]
