# Generated by Django 3.0.5 on 2020-07-05 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200705_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coms',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 1, 0, 40, 972902)),
        ),
    ]
