# Generated by Django 3.0.5 on 2020-07-06 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200706_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('firstname', models.TextField(max_length=100)),
                ('lastname', models.TextField(max_length=100)),
                ('pass1', models.TextField(max_length=100)),
                ('pass2', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 22, 28, 24, 931307)),
        ),
    ]
