# Generated by Django 3.0.5 on 2020-07-06 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200706_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 1, 15, 29, 604957)),
        ),
    ]
